import type { ComponentType } from 'react';
// UI tab — Lucide (only file that imports react-icons/lu; chrome stays on vsc)
import {
  LuActivity,
  LuAlarmClock,
  LuAnchor,
  LuArchive,
  LuArrowDown,
  LuArrowLeft,
  LuArrowRight,
  LuArrowUp,
  LuBattery,
  LuBell,
  LuBook,
  LuBookmark,
  LuBox,
  LuBriefcase,
  LuCamera,
  LuCar,
  LuCheck,
  LuCircle,
  LuClipboard,
  LuClock,
  LuCloud,
  LuCode,
  LuCoffee,
  LuCompass,
  LuCopy,
  LuCpu,
  LuCreditCard,
  LuCrop,
  LuCrosshair,
  LuDatabase,
  LuDiamond,
  LuDownload,
  LuDroplet,
  LuEraser,
  LuEye,
  LuFeather,
  LuFile,
  LuFilter,
  LuFlag,
  LuFlame,
  LuFolder,
  LuGift,
  LuGlobe,
  LuGrid2X2,
  LuHash,
  LuHeadphones,
  LuHeart,
  LuHexagon,
  LuHouse,
  LuImage,
  LuInbox,
  LuInfo,
  LuKey,
  LuKeyboard,
  LuLayers,
  LuLeaf,
  LuLightbulb,
  LuLink,
  LuList,
  LuLock,
  LuLockOpen,
  LuLogIn,
  LuLogOut,
  LuMail,
  LuMap,
  LuMapPin,
  LuMaximize,
  LuMegaphone,
  LuMessageCircle,
  LuMic,
  LuMinimize,
  LuMonitor,
  LuMoon,
  LuMousePointer,
  LuMove,
  LuMusic,
  LuOctagon,
  LuPaintbrush,
  LuPalette,
  LuPaperclip,
  LuPencil,
  LuPhone,
  LuPin,
  LuPlay,
  LuPlus,
  LuPower,
  LuPrinter,
  LuPuzzle,
  LuRefreshCw,
  LuRocket,
  LuRotateCw,
  LuRuler,
  LuSearch,
  LuSend,
  LuServer,
  LuSettings,
  LuShield,
  LuShoppingBag,
  LuShoppingCart,
  LuSmartphone,
  LuSparkles,
  LuSquare,
  LuStar,
  LuSun,
  LuTag,
  LuTarget,
  LuTerminal,
  LuTimer,
  LuTrash,
  LuTrendingUp,
  LuTriangle,
  LuTrophy,
  LuTruck,
  LuUmbrella,
  LuUpload,
  LuUser,
  LuVideo,
  LuVolume2,
  LuWallet,
  LuWand,
  LuWatch,
  LuWifi,
  LuWrench,
  LuX,
  LuZap,
} from 'react-icons/lu';
// Brands tab — Simple Icons (only file that imports react-icons/si; chrome stays on vsc)
import {
  SiAirbnb,
  SiAndroid,
  SiApple,
  SiAtlassian,
  SiBitbucket,
  SiCanva,
  SiCloudflare,
  SiCodepen,
  SiConfluence,
  SiCss,
  SiDiscord,
  SiDocker,
  SiDropbox,
  SiFacebook,
  SiFigma,
  SiFirebase,
  SiFramer,
  SiGit,
  SiGithub,
  SiGitlab,
  SiGo,
  SiGoogle,
  SiGooglechrome,
  SiGoogledrive,
  SiGraphql,
  SiHeroku,
  SiHtml5,
  SiInstagram,
  SiIntellijidea,
  SiJavascript,
  SiJest,
  SiJira,
  SiKubernetes,
  SiLinear,
  SiLinux,
  SiMaterialdesign,
  SiMongodb,
  SiMysql,
  SiNetflix,
  SiNetlify,
  SiNextdotjs,
  SiNodedotjs,
  SiNotion,
  SiNpm,
  SiOpenai,
  SiPostgresql,
  SiPostman,
  SiPrettier,
  SiPrisma,
  SiPython,
  SiReact,
  SiRedis,
  SiRedux,
  SiRuby,
  SiRust,
  SiSass,
  SiSentry,
  SiSketch,
  SiSlack,
  SiSpotify,
  SiStackoverflow,
  SiStorybook,
  SiStripe,
  SiSupabase,
  SiSvelte,
  SiSwift,
  SiTailwindcss,
  SiTelegram,
  SiTrello,
  SiTwitch,
  SiTypescript,
  SiVercel,
  SiVite,
  SiVuedotjs,
  SiWebpack,
  SiWhatsapp,
  SiWordpress,
  SiX,
  SiYoutube,
  SiZoom,
} from 'react-icons/si';
// Code tab — Codicons (project house set)
import {
  VscAccount,
  VscAdd,
  VscArchive,
  VscArrowDown,
  VscArrowLeft,
  VscArrowRight,
  VscArrowUp,
  VscBeaker,
  VscBell,
  VscBook,
  VscBookmark,
  VscBriefcase,
  VscBug,
  VscCalendar,
  VscCheck,
  VscClose,
  VscCloud,
  VscCloudDownload,
  VscCloudUpload,
  VscCode,
  VscComment,
  VscCopy,
  VscDashboard,
  VscDatabase,
  VscDebug,
  VscDeviceMobile,
  VscEdit,
  VscEye,
  VscFile,
  VscFiles,
  VscFilter,
  VscFlame,
  VscFolder,
  VscFolderOpened,
  VscGear,
  VscGift,
  VscGithub,
  VscGitMerge,
  VscGitPullRequest,
  VscGlobe,
  VscGraph,
  VscHeart,
  VscHistory,
  VscHome,
  VscInbox,
  VscInfo,
  VscIssues,
  VscKey,
  VscLayers,
  VscLayout,
  VscLightbulb,
  VscLink,
  VscLocation,
  VscLock,
  VscMail,
  VscMegaphone,
  VscMortarBoard,
  VscMusic,
  VscNewFile,
  VscNewFolder,
  VscOrganization,
  VscOutput,
  VscPackage,
  VscPaintcan,
  VscPerson,
  VscPin,
  VscPlay,
  VscProject,
  VscPulse,
  VscQuestion,
  VscRefresh,
  VscReport,
  VscRobot,
  VscRocket,
  VscRss,
  VscRunAll,
  VscSave,
  VscSearch,
  VscSend,
  VscServer,
  VscSettings,
  VscShield,
  VscSignIn,
  VscSignOut,
  VscSmiley,
  VscStarFull,
  VscSync,
  VscTag,
  VscTarget,
  VscTasklist,
  VscTerminal,
  VscThumbsdown,
  VscThumbsup,
  VscTools,
  VscTrash,
  VscVerified,
  VscWand,
  VscWarning,
  VscWatch,
  VscZoomIn,
  VscZoomOut,
} from 'react-icons/vsc';

type IconComponent = ComponentType<{ size?: number; 'aria-hidden'?: boolean | 'true' }>;

export interface IconEntry {
  token: string;
  // Exactly one of Icon or label is set — invariant enforced by construction.
  Icon?: IconComponent;
  label?: string;
  /** @deprecated legacy SVG-string field — kept only for type compat during migration; always undefined post-refactor */
  svg?: never;
}

export const PICKER_ICONS: Record<string, IconEntry[]> = {
  code: [
    { token: 'vsc:VscFile', Icon: VscFile },
    { token: 'vsc:VscFiles', Icon: VscFiles },
    { token: 'vsc:VscFolder', Icon: VscFolder },
    { token: 'vsc:VscFolderOpened', Icon: VscFolderOpened },
    { token: 'vsc:VscNewFile', Icon: VscNewFile },
    { token: 'vsc:VscNewFolder', Icon: VscNewFolder },
    { token: 'vsc:VscGear', Icon: VscGear },
    { token: 'vsc:VscSettings', Icon: VscSettings },
    { token: 'vsc:VscTools', Icon: VscTools },
    { token: 'vsc:VscKey', Icon: VscKey },
    { token: 'vsc:VscLock', Icon: VscLock },
    { token: 'vsc:VscShield', Icon: VscShield },
    { token: 'vsc:VscVerified', Icon: VscVerified },
    { token: 'vsc:VscEdit', Icon: VscEdit },
    { token: 'vsc:VscSave', Icon: VscSave },
    { token: 'vsc:VscCopy', Icon: VscCopy },
    { token: 'vsc:VscTrash', Icon: VscTrash },
    { token: 'vsc:VscRefresh', Icon: VscRefresh },
    { token: 'vsc:VscSync', Icon: VscSync },
    { token: 'vsc:VscAdd', Icon: VscAdd },
    { token: 'vsc:VscClose', Icon: VscClose },
    { token: 'vsc:VscCheck', Icon: VscCheck },
    { token: 'vsc:VscSearch', Icon: VscSearch },
    { token: 'vsc:VscFilter', Icon: VscFilter },
    { token: 'vsc:VscInfo', Icon: VscInfo },
    { token: 'vsc:VscWarning', Icon: VscWarning },
    { token: 'vsc:VscQuestion', Icon: VscQuestion },
    { token: 'vsc:VscBug', Icon: VscBug },
    { token: 'vsc:VscDebug', Icon: VscDebug },
    { token: 'vsc:VscBeaker', Icon: VscBeaker },
    { token: 'vsc:VscComment', Icon: VscComment },
    { token: 'vsc:VscEye', Icon: VscEye },
    { token: 'vsc:VscHistory', Icon: VscHistory },
    { token: 'vsc:VscWatch', Icon: VscWatch },
    { token: 'vsc:VscCalendar', Icon: VscCalendar },
    { token: 'vsc:VscRobot', Icon: VscRobot },
    { token: 'vsc:VscWand', Icon: VscWand },
    { token: 'vsc:VscRocket', Icon: VscRocket },
    { token: 'vsc:VscHome', Icon: VscHome },
    { token: 'vsc:VscBell', Icon: VscBell },
    { token: 'vsc:VscMail', Icon: VscMail },
    { token: 'vsc:VscInbox', Icon: VscInbox },
    { token: 'vsc:VscMegaphone', Icon: VscMegaphone },
    { token: 'vsc:VscLink', Icon: VscLink },
    { token: 'vsc:VscLocation', Icon: VscLocation },
    { token: 'vsc:VscPin', Icon: VscPin },
    { token: 'vsc:VscBookmark', Icon: VscBookmark },
    { token: 'vsc:VscTag', Icon: VscTag },
    { token: 'vsc:VscTarget', Icon: VscTarget },
    { token: 'vsc:VscTasklist', Icon: VscTasklist },
    { token: 'vsc:VscProject', Icon: VscProject },
    { token: 'vsc:VscDashboard', Icon: VscDashboard },
    { token: 'vsc:VscLayout', Icon: VscLayout },
    { token: 'vsc:VscLayers', Icon: VscLayers },
    { token: 'vsc:VscGraph', Icon: VscGraph },
    { token: 'vsc:VscPulse', Icon: VscPulse },
    { token: 'vsc:VscReport', Icon: VscReport },
    { token: 'vsc:VscOutput', Icon: VscOutput },
    { token: 'vsc:VscTerminal', Icon: VscTerminal },
    { token: 'vsc:VscCode', Icon: VscCode },
    { token: 'vsc:VscPackage', Icon: VscPackage },
    { token: 'vsc:VscDatabase', Icon: VscDatabase },
    { token: 'vsc:VscServer', Icon: VscServer },
    { token: 'vsc:VscCloud', Icon: VscCloud },
    { token: 'vsc:VscCloudDownload', Icon: VscCloudDownload },
    { token: 'vsc:VscCloudUpload', Icon: VscCloudUpload },
    { token: 'vsc:VscGlobe', Icon: VscGlobe },
    { token: 'vsc:VscGithub', Icon: VscGithub },
    { token: 'vsc:VscGitMerge', Icon: VscGitMerge },
    { token: 'vsc:VscGitPullRequest', Icon: VscGitPullRequest },
    { token: 'vsc:VscIssues', Icon: VscIssues },
    { token: 'vsc:VscRss', Icon: VscRss },
    { token: 'vsc:VscRunAll', Icon: VscRunAll },
    { token: 'vsc:VscPlay', Icon: VscPlay },
    { token: 'vsc:VscSend', Icon: VscSend },
    { token: 'vsc:VscSignIn', Icon: VscSignIn },
    { token: 'vsc:VscSignOut', Icon: VscSignOut },
    { token: 'vsc:VscPerson', Icon: VscPerson },
    { token: 'vsc:VscAccount', Icon: VscAccount },
    { token: 'vsc:VscOrganization', Icon: VscOrganization },
    { token: 'vsc:VscBook', Icon: VscBook },
    { token: 'vsc:VscMortarBoard', Icon: VscMortarBoard },
    { token: 'vsc:VscBriefcase', Icon: VscBriefcase },
    { token: 'vsc:VscGift', Icon: VscGift },
    { token: 'vsc:VscHeart', Icon: VscHeart },
    { token: 'vsc:VscFlame', Icon: VscFlame },
    { token: 'vsc:VscLightbulb', Icon: VscLightbulb },
    { token: 'vsc:VscPaintcan', Icon: VscPaintcan },
    { token: 'vsc:VscMusic', Icon: VscMusic },
    { token: 'vsc:VscDeviceMobile', Icon: VscDeviceMobile },
    { token: 'vsc:VscArchive', Icon: VscArchive },
    { token: 'vsc:VscThumbsup', Icon: VscThumbsup },
    { token: 'vsc:VscThumbsdown', Icon: VscThumbsdown },
    { token: 'vsc:VscSmiley', Icon: VscSmiley },
    { token: 'vsc:VscStarFull', Icon: VscStarFull },
    { token: 'vsc:VscArrowUp', Icon: VscArrowUp },
    { token: 'vsc:VscArrowDown', Icon: VscArrowDown },
    { token: 'vsc:VscArrowLeft', Icon: VscArrowLeft },
    { token: 'vsc:VscArrowRight', Icon: VscArrowRight },
    { token: 'vsc:VscZoomIn', Icon: VscZoomIn },
    { token: 'vsc:VscZoomOut', Icon: VscZoomOut },
  ],
  brands: [
    { token: 'brand:github', Icon: SiGithub },
    { token: 'brand:gitlab', Icon: SiGitlab },
    { token: 'brand:bitbucket', Icon: SiBitbucket },
    { token: 'brand:git', Icon: SiGit },
    { token: 'brand:figma', Icon: SiFigma },
    { token: 'brand:sketch', Icon: SiSketch },
    { token: 'brand:framer', Icon: SiFramer },
    { token: 'brand:canva', Icon: SiCanva },
    { token: 'brand:material', Icon: SiMaterialdesign },
    { token: 'brand:storybook', Icon: SiStorybook },
    { token: 'brand:react', Icon: SiReact },
    { token: 'brand:vue', Icon: SiVuedotjs },
    { token: 'brand:svelte', Icon: SiSvelte },
    { token: 'brand:redux', Icon: SiRedux },
    // SiNextdotjs is Simple-Icons' name for Next.js; the stored token stays brand:nextjs
    { token: 'brand:nextjs', Icon: SiNextdotjs },
    { token: 'brand:nodejs', Icon: SiNodedotjs },
    { token: 'brand:typescript', Icon: SiTypescript },
    { token: 'brand:javascript', Icon: SiJavascript },
    { token: 'brand:html5', Icon: SiHtml5 },
    { token: 'brand:css3', Icon: SiCss },
    { token: 'brand:tailwind', Icon: SiTailwindcss },
    { token: 'brand:sass', Icon: SiSass },
    { token: 'brand:vite', Icon: SiVite },
    { token: 'brand:webpack', Icon: SiWebpack },
    { token: 'brand:npm', Icon: SiNpm },
    { token: 'brand:prettier', Icon: SiPrettier },
    { token: 'brand:jest', Icon: SiJest },
    { token: 'brand:graphql', Icon: SiGraphql },
    { token: 'brand:prisma', Icon: SiPrisma },
    { token: 'brand:postgres', Icon: SiPostgresql },
    { token: 'brand:mysql', Icon: SiMysql },
    { token: 'brand:mongodb', Icon: SiMongodb },
    { token: 'brand:redis', Icon: SiRedis },
    { token: 'brand:supabase', Icon: SiSupabase },
    { token: 'brand:firebase', Icon: SiFirebase },
    { token: 'brand:docker', Icon: SiDocker },
    { token: 'brand:kubernetes', Icon: SiKubernetes },
    { token: 'brand:vercel', Icon: SiVercel },
    { token: 'brand:netlify', Icon: SiNetlify },
    { token: 'brand:heroku', Icon: SiHeroku },
    { token: 'brand:cloudflare', Icon: SiCloudflare },
    { token: 'brand:google', Icon: SiGoogle },
    { token: 'brand:googlechrome', Icon: SiGooglechrome },
    { token: 'brand:googledrive', Icon: SiGoogledrive },
    { token: 'brand:apple', Icon: SiApple },
    { token: 'brand:android', Icon: SiAndroid },
    { token: 'brand:linux', Icon: SiLinux },
    { token: 'brand:python', Icon: SiPython },
    { token: 'brand:go', Icon: SiGo },
    { token: 'brand:rust', Icon: SiRust },
    { token: 'brand:ruby', Icon: SiRuby },
    { token: 'brand:swift', Icon: SiSwift },
    { token: 'brand:openai', Icon: SiOpenai },
    { token: 'brand:notion', Icon: SiNotion },
    { token: 'brand:linear', Icon: SiLinear },
    { token: 'brand:jira', Icon: SiJira },
    { token: 'brand:trello', Icon: SiTrello },
    { token: 'brand:atlassian', Icon: SiAtlassian },
    { token: 'brand:confluence', Icon: SiConfluence },
    { token: 'brand:intellij', Icon: SiIntellijidea },
    { token: 'brand:postman', Icon: SiPostman },
    { token: 'brand:codepen', Icon: SiCodepen },
    { token: 'brand:slack', Icon: SiSlack },
    { token: 'brand:discord', Icon: SiDiscord },
    { token: 'brand:telegram', Icon: SiTelegram },
    { token: 'brand:whatsapp', Icon: SiWhatsapp },
    { token: 'brand:zoom', Icon: SiZoom },
    { token: 'brand:dropbox', Icon: SiDropbox },
    { token: 'brand:stripe', Icon: SiStripe },
    { token: 'brand:wordpress', Icon: SiWordpress },
    { token: 'brand:airbnb', Icon: SiAirbnb },
    { token: 'brand:spotify', Icon: SiSpotify },
    { token: 'brand:netflix', Icon: SiNetflix },
    { token: 'brand:facebook', Icon: SiFacebook },
    { token: 'brand:instagram', Icon: SiInstagram },
    { token: 'brand:x', Icon: SiX },
    { token: 'brand:youtube', Icon: SiYoutube },
    { token: 'brand:twitch', Icon: SiTwitch },
    { token: 'brand:stackoverflow', Icon: SiStackoverflow },
    { token: 'brand:sentry', Icon: SiSentry },
  ],
  ui: [
    { token: 'ui:square', Icon: LuSquare },
    { token: 'ui:circle', Icon: LuCircle },
    { token: 'ui:triangle', Icon: LuTriangle },
    { token: 'ui:hexagon', Icon: LuHexagon },
    { token: 'ui:octagon', Icon: LuOctagon },
    { token: 'ui:diamond', Icon: LuDiamond },
    { token: 'ui:star', Icon: LuStar },
    { token: 'ui:heart', Icon: LuHeart },
    { token: 'ui:flag', Icon: LuFlag },
    { token: 'ui:pin', Icon: LuPin },
    { token: 'ui:plus', Icon: LuPlus },
    { token: 'ui:x', Icon: LuX },
    { token: 'ui:check', Icon: LuCheck },
    { token: 'ui:mousePointer', Icon: LuMousePointer },
    { token: 'ui:move', Icon: LuMove },
    { token: 'ui:crop', Icon: LuCrop },
    { token: 'ui:crosshair', Icon: LuCrosshair },
    { token: 'ui:target', Icon: LuTarget },
    { token: 'ui:compass', Icon: LuCompass },
    { token: 'ui:map', Icon: LuMap },
    { token: 'ui:mapPin', Icon: LuMapPin },
    { token: 'ui:anchor', Icon: LuAnchor },
    { token: 'ui:layers', Icon: LuLayers },
    { token: 'ui:grid', Icon: LuGrid2X2 },
    { token: 'ui:list', Icon: LuList },
    { token: 'ui:image', Icon: LuImage },
    { token: 'ui:palette', Icon: LuPalette },
    { token: 'ui:paintbrush', Icon: LuPaintbrush },
    { token: 'ui:pencil', Icon: LuPencil },
    { token: 'ui:feather', Icon: LuFeather },
    { token: 'ui:eraser', Icon: LuEraser },
    { token: 'ui:ruler', Icon: LuRuler },
    { token: 'ui:droplet', Icon: LuDroplet },
    { token: 'ui:sparkles', Icon: LuSparkles },
    { token: 'ui:flame', Icon: LuFlame },
    { token: 'ui:leaf', Icon: LuLeaf },
    { token: 'ui:sun', Icon: LuSun },
    { token: 'ui:moon', Icon: LuMoon },
    { token: 'ui:cloud', Icon: LuCloud },
    { token: 'ui:zap', Icon: LuZap },
    { token: 'ui:lightbulb', Icon: LuLightbulb },
    { token: 'ui:eye', Icon: LuEye },
    { token: 'ui:key', Icon: LuKey },
    { token: 'ui:lock', Icon: LuLock },
    { token: 'ui:unlock', Icon: LuLockOpen },
    { token: 'ui:shield', Icon: LuShield },
    { token: 'ui:home', Icon: LuHouse },
    { token: 'ui:user', Icon: LuUser },
    { token: 'ui:bell', Icon: LuBell },
    { token: 'ui:mail', Icon: LuMail },
    { token: 'ui:inbox', Icon: LuInbox },
    { token: 'ui:phone', Icon: LuPhone },
    { token: 'ui:megaphone', Icon: LuMegaphone },
    { token: 'ui:messageCircle', Icon: LuMessageCircle },
    { token: 'ui:mic', Icon: LuMic },
    { token: 'ui:headphones', Icon: LuHeadphones },
    { token: 'ui:speaker', Icon: LuVolume2 },
    { token: 'ui:music', Icon: LuMusic },
    { token: 'ui:camera', Icon: LuCamera },
    { token: 'ui:video', Icon: LuVideo },
    { token: 'ui:film', Icon: LuFilter },
    { token: 'ui:book', Icon: LuBook },
    { token: 'ui:bookmark', Icon: LuBookmark },
    { token: 'ui:tag', Icon: LuTag },
    { token: 'ui:gift', Icon: LuGift },
    { token: 'ui:wand', Icon: LuWand },
    { token: 'ui:rocket', Icon: LuRocket },
    { token: 'ui:plane', Icon: LuSend },
    { token: 'ui:car', Icon: LuCar },
    { token: 'ui:truck', Icon: LuTruck },
    { token: 'ui:umbrella', Icon: LuUmbrella },
    { token: 'ui:shoppingCart', Icon: LuShoppingCart },
    { token: 'ui:shoppingBag', Icon: LuShoppingBag },
    { token: 'ui:creditCard', Icon: LuCreditCard },
    { token: 'ui:wallet', Icon: LuWallet },
    { token: 'ui:coffee', Icon: LuCoffee },
    { token: 'ui:briefcase', Icon: LuBriefcase },
    { token: 'ui:archive', Icon: LuArchive },
    { token: 'ui:clipboard', Icon: LuClipboard },
    { token: 'ui:copy', Icon: LuCopy },
    { token: 'ui:file', Icon: LuFile },
    { token: 'ui:folder', Icon: LuFolder },
    { token: 'ui:link', Icon: LuLink },
    { token: 'ui:paperclip', Icon: LuPaperclip },
    { token: 'ui:trash', Icon: LuTrash },
    { token: 'ui:download', Icon: LuDownload },
    { token: 'ui:upload', Icon: LuUpload },
    { token: 'ui:refresh', Icon: LuRefreshCw },
    { token: 'ui:rotate', Icon: LuRotateCw },
    { token: 'ui:settings', Icon: LuSettings },
    { token: 'ui:wrench', Icon: LuWrench },
    { token: 'ui:terminal', Icon: LuTerminal },
    { token: 'ui:code', Icon: LuCode },
    { token: 'ui:database', Icon: LuDatabase },
    { token: 'ui:server', Icon: LuServer },
    { token: 'ui:cpu', Icon: LuCpu },
    { token: 'ui:monitor', Icon: LuMonitor },
    { token: 'ui:smartphone', Icon: LuSmartphone },
    { token: 'ui:keyboard', Icon: LuKeyboard },
    { token: 'ui:wifi', Icon: LuWifi },
    { token: 'ui:globe', Icon: LuGlobe },
    { token: 'ui:battery', Icon: LuBattery },
    { token: 'ui:power', Icon: LuPower },
    { token: 'ui:plug', Icon: LuPlay },
    { token: 'ui:puzzle', Icon: LuPuzzle },
    { token: 'ui:box', Icon: LuBox },
    { token: 'ui:trophy', Icon: LuTrophy },
    { token: 'ui:trendingUp', Icon: LuTrendingUp },
    { token: 'ui:activity', Icon: LuActivity },
    { token: 'ui:hash', Icon: LuHash },
    { token: 'ui:clock', Icon: LuClock },
    { token: 'ui:timer', Icon: LuTimer },
    { token: 'ui:alarm', Icon: LuAlarmClock },
    { token: 'ui:watch', Icon: LuWatch },
    { token: 'ui:logIn', Icon: LuLogIn },
    { token: 'ui:logOut', Icon: LuLogOut },
    { token: 'ui:info', Icon: LuInfo },
    { token: 'ui:search', Icon: LuSearch },
    { token: 'ui:filter', Icon: LuFilter },
    { token: 'ui:maximize', Icon: LuMaximize },
    { token: 'ui:minimize', Icon: LuMinimize },
    { token: 'ui:arrowUp', Icon: LuArrowUp },
    { token: 'ui:arrowDown', Icon: LuArrowDown },
    { token: 'ui:arrowLeft', Icon: LuArrowLeft },
    { token: 'ui:arrowRight', Icon: LuArrowRight },
    { token: 'ui:printer', Icon: LuPrinter },
  ],
  emoji: [
    { token: 'emoji:🎨', label: '🎨' },
    { token: 'emoji:📐', label: '📐' },
    { token: 'emoji:📱', label: '📱' },
    { token: 'emoji:💻', label: '💻' },
    { token: 'emoji:🖥', label: '🖥' },
    { token: 'emoji:⌨', label: '⌨' },
    { token: 'emoji:🖼', label: '🖼' },
    { token: 'emoji:📁', label: '📁' },
    { token: 'emoji:📂', label: '📂' },
    { token: 'emoji:🗂', label: '🗂' },
    { token: 'emoji:📦', label: '📦' },
    { token: 'emoji:📚', label: '📚' },
    { token: 'emoji:📖', label: '📖' },
    { token: 'emoji:📝', label: '📝' },
    { token: 'emoji:📌', label: '📌' },
    { token: 'emoji:📎', label: '📎' },
    { token: 'emoji:🔖', label: '🔖' },
    { token: 'emoji:🏷', label: '🏷' },
    { token: 'emoji:🎯', label: '🎯' },
    { token: 'emoji:🎲', label: '🎲' },
    { token: 'emoji:🧩', label: '🧩' },
    { token: 'emoji:🎮', label: '🎮' },
    { token: 'emoji:🔥', label: '🔥' },
    { token: 'emoji:⚡', label: '⚡' },
    { token: 'emoji:✨', label: '✨' },
    { token: 'emoji:💫', label: '💫' },
    { token: 'emoji:🌟', label: '🌟' },
    { token: 'emoji:💡', label: '💡' },
    { token: 'emoji:🎉', label: '🎉' },
    { token: 'emoji:🎊', label: '🎊' },
    { token: 'emoji:🚀', label: '🚀' },
    { token: 'emoji:🛸', label: '🛸' },
    { token: 'emoji:🪐', label: '🪐' },
    { token: 'emoji:🌍', label: '🌍' },
    { token: 'emoji:🌐', label: '🌐' },
    { token: 'emoji:🗺', label: '🗺' },
    { token: 'emoji:🧭', label: '🧭' },
    { token: 'emoji:🔮', label: '🔮' },
    { token: 'emoji:🎭', label: '🎭' },
    { token: 'emoji:🎪', label: '🎪' },
    { token: 'emoji:🎸', label: '🎸' },
    { token: 'emoji:🎹', label: '🎹' },
    { token: 'emoji:🎺', label: '🎺' },
    { token: 'emoji:🎻', label: '🎻' },
    { token: 'emoji:🎼', label: '🎼' },
    { token: 'emoji:🎵', label: '🎵' },
    { token: 'emoji:🎶', label: '🎶' },
    { token: 'emoji:🎤', label: '🎤' },
    { token: 'emoji:🎧', label: '🎧' },
    { token: 'emoji:📷', label: '📷' },
    { token: 'emoji:📹', label: '📹' },
    { token: 'emoji:🎥', label: '🎥' },
    { token: 'emoji:📸', label: '📸' },
    { token: 'emoji:☕', label: '☕' },
    { token: 'emoji:🍵', label: '🍵' },
    { token: 'emoji:🍕', label: '🍕' },
    { token: 'emoji:🍔', label: '🍔' },
    { token: 'emoji:🍩', label: '🍩' },
    { token: 'emoji:🍰', label: '🍰' },
    { token: 'emoji:🥑', label: '🥑' },
    { token: 'emoji:🌱', label: '🌱' },
    { token: 'emoji:🌿', label: '🌿' },
    { token: 'emoji:🍀', label: '🍀' },
    { token: 'emoji:🌸', label: '🌸' },
    { token: 'emoji:🌻', label: '🌻' },
    { token: 'emoji:🌈', label: '🌈' },
    { token: 'emoji:☀', label: '☀' },
    { token: 'emoji:🌙', label: '🌙' },
    { token: 'emoji:⛅', label: '⛅' },
    { token: 'emoji:☁', label: '☁' },
    { token: 'emoji:🌧', label: '🌧' },
    { token: 'emoji:❄', label: '❄' },
    { token: 'emoji:🐶', label: '🐶' },
    { token: 'emoji:🐱', label: '🐱' },
    { token: 'emoji:🦊', label: '🦊' },
    { token: 'emoji:🐼', label: '🐼' },
    { token: 'emoji:🐧', label: '🐧' },
    { token: 'emoji:🦄', label: '🦄' },
    { token: 'emoji:🐝', label: '🐝' },
    { token: 'emoji:🦋', label: '🦋' },
    { token: 'emoji:🐢', label: '🐢' },
    { token: 'emoji:🐙', label: '🐙' },
    { token: 'emoji:🦀', label: '🦀' },
    { token: 'emoji:🐬', label: '🐬' },
    { token: 'emoji:❤', label: '❤' },
    { token: 'emoji:🧡', label: '🧡' },
    { token: 'emoji:💛', label: '💛' },
    { token: 'emoji:💚', label: '💚' },
    { token: 'emoji:💙', label: '💙' },
    { token: 'emoji:💜', label: '💜' },
    { token: 'emoji:🖤', label: '🖤' },
    { token: 'emoji:🤍', label: '🤍' },
    { token: 'emoji:💎', label: '💎' },
    { token: 'emoji:👑', label: '👑' },
    { token: 'emoji:🏆', label: '🏆' },
    { token: 'emoji:🎖', label: '🎖' },
    { token: 'emoji:🥇', label: '🥇' },
    { token: 'emoji:⭐', label: '⭐' },
    { token: 'emoji:✅', label: '✅' },
    { token: 'emoji:❎', label: '❎' },
    { token: 'emoji:⚠', label: '⚠' },
    { token: 'emoji:🔒', label: '🔒' },
    { token: 'emoji:🔓', label: '🔓' },
    { token: 'emoji:🔑', label: '🔑' },
    { token: 'emoji:🛠', label: '🛠' },
    { token: 'emoji:🧪', label: '🧪' },
    { token: 'emoji:🧰', label: '🧰' },
    { token: 'emoji:📊', label: '📊' },
    { token: 'emoji:📈', label: '📈' },
    { token: 'emoji:📉', label: '📉' },
  ],
};

export function filterIcons(tab: string, query: string): IconEntry[] {
  const icons = PICKER_ICONS[tab] ?? [];
  if (!query) return icons;
  const q = query.toLowerCase();
  return icons.filter((i) => i.token.toLowerCase().includes(q));
}

export type ResolvedIcon = { kind: 'icon'; Icon: IconComponent } | { kind: 'emoji'; glyph: string };

// Token → entry lookup map, built once at module load. Resolution runs
// once per tree node render, so a Map saves repeated linear scans across
// the ~350 entries in PICKER_ICONS.
const TOKEN_INDEX: Map<string, IconEntry> = new Map();
for (const group of Object.values(PICKER_ICONS)) {
  for (const entry of group) TOKEN_INDEX.set(entry.token, entry);
}

/**
 * Resolve a stored icon token (e.g. `vsc:VscFile`, `emoji:🚀`) to a
 * typed descriptor. Returns `null` for unknown tokens so the caller can
 * fall back to a default glyph.
 *
 * Single source of truth for icon resolution across the project tree,
 * folder header, and project-card surfaces.
 */
export function resolveIconToken(token: string): ResolvedIcon | null {
  if (token.startsWith('emoji:')) {
    return { kind: 'emoji', glyph: token.slice(6) };
  }
  const entry = TOKEN_INDEX.get(token);
  if (entry?.Icon) return { kind: 'icon', Icon: entry.Icon };
  if (entry?.label) return { kind: 'emoji', glyph: entry.label };
  return null;
}
